name: Build
on:
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: ${{ matrix.os-name }} build (${{ matrix.profile-name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - windows-2022
          - ubuntu-22.04
          # - macos-12
        profile:
          - dev
          - release
        include:
          # - os: windows-2022
          #   os-name: Windows
          - os: ubuntu-22.04
            os-name: Ubuntu
          # - os: macos-12
          #   os-name: MacOS
          - profile: dev
            profile-name: development
            profile-flag-rs: ''
            profile-flag-net: Debug
          - profile: release
            profile-name: release
            profile-flag-rs: '--release'
            profile-flag-net: Release
    steps:
      - uses: actions/checkout@v3
      - name: Build native code
        run: |
          cd Native
          cargo build --verbose ${{ matrix.profile-flag-rs }}
      # - name: Dump native output tree (TEMPORARY)
      #   run: |
      #     cd Native
      #     find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      - name: Run native tests
        run: |
          cd Native
          cargo test ${{ matrix.profile-flag-rs }}
      - name: Build managed code
        run: |
          cd Managed
          dotnet build -c ${{ matrix.profile-flag-net }} --verbosity normal
      - name: Run managed tests
        run: |
          dotnet test -c ${{ matrix.profile-flag-net }} --verbosity normal
